### ISSUE TITLE
Table of Contents links in documentation are broken

### ISSUE THREAD

**Issue by khamaileon** [araichev/gtfs_kit#32]
Hello,

I noticed that the Table of Contents links in the GTFS Kit documentation are not working correctly. Each URL contains #document-modules in addition to the section anchor, which breaks navigation.

For example, the current link:

https://mrcagney.github.io/gtfs_kit_docs/#document-modules#gtfs_kit.miscellany.restrict_to_dates

should be:

https://mrcagney.github.io/gtfs_kit_docs/#gtfs_kit.miscellany.restrict_to_dates

Could you please update the links so they point to the correct sections?

Thank you!

**Comment by araichev** [comment]
Thank @khamaileon for finding that error and suggesting a fix. 
Fixed now.

**Comment by khamaileon** [comment]
Hello @araichev, thanks for the reply. I can see that the documentation has been updated, but the issue remains. The links in the left menu are invalid.

**Comment by araichev** [comment]
THanks @khamaileon . I now see that my local docs builder works but not the production docs builder. Will fix that today.

**Comment by araichev** [comment]
OK, fixed for real now. I appreciate your quality control.
